# Generated by Django 3.1.7 on 2021-04-01 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babyoda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensagem',
            new_name='Mensagens',
        ),
    ]
